USE TESTE_ICARO
GO

CREATE TABLE ESTADOS(
	ID_ESTADO INT IDENTITY(1,1) NOT NULL,
	NOME_ESTADO VARCHAR(30) NOT NULL,
	NOME_PAIS VARCHAR(30) NOT NULL,
	
	CONSTRAINT PK_ID_ESTADO PRIMARY KEY (ID_ESTADO)
)
GO

CREATE TABLE CIDADES(
	ID_CIDADE INT IDENTITY(1,1) NOT NULL,
	NOME_CIDADE VARCHAR(30) NOT NULL,
	ID_ESTADO INT NOT NULL,
	COD_POSTAL INT NULL

	CONSTRAINT PK_ID_CIDADE PRIMARY KEY (ID_CIDADE),

	CONSTRAINT FK_ID_ESTADO__CIDADES FOREIGN KEY (ID_ESTADO)
	REFERENCES ESTADOS (ID_ESTADO)
)
GO

CREATE TABLE CLIENTES(
	 ID_CLIENTE INT IDENTITY(1,1) NOT NULL,
	 NOME_CLIENTE VARCHAR(100) NOT NULL,
	 TELEFONE1 VARCHAR(14) NOT NULL,
	 TELEFONE2 VARCHAR(14) NULL,
	 LOGRADOURO VARCHAR(150) NULL,
	 COMPLEMENTO VARCHAR (50) NULL, 
	 NUMERO_CASA SMALLINT NULL,
	 ID_CIDADE INT NULL,
	 ID_ESTADO INT NULL, 
	 CPF VARCHAR(14) NULL,
	 CNPJ VARCHAR(18) NULL,
	 RG VARCHAR(10) NULL,
	 EMAIL VARCHAR(30)NULL,
	 GENERO CHAR NOT NULL,
	 OBSERVAÇÕES VARCHAR (500) NULL,
	 WHATSAPP VARCHAR(14) NOT NULL

	 CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE),
	 
	 CONSTRAINT FK_ID_CIDADE__CLIENTES FOREIGN KEY (ID_CIDADE)
	 REFERENCES CIDADES (ID_CIDADE), 

	 CONSTRAINT FK_ID_ESTADO__CLIENTES FOREIGN KEY (ID_ESTADO)
	 REFERENCES ESTADOS (ID_ESTADO)
)
GO

CREATE TABLE VEICULOS(
	ID_VEICULO INT IDENTITY(1,1) NOT NULL,
	PLACA VARCHAR(7) UNIQUE NOT NULL,
	TIPO_VEICULO VARCHAR(10) NOT NULL,
	COR VARCHAR(15) NOT NULL,
	ANO_MODELO SMALLINT NULL,
	MODELO_VEICULO VARCHAR(10) NOT NULL,
	OBSERVAÇÕES VARCHAR(500) NULL

	CONSTRAINT PK_ID_VEICULO PRIMARY KEY (ID_VEICULO)
)
GO

CREATE TABLE CLIENTES_VEICULOS(
	ID_CLIENTE INT NOT NULL,
	ID_VEICULO INT NOT NULL,

	CONSTRAINT FK_ID_CLIENTE__CLIENTES_VEICULOS FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTES (ID_CLIENTE),

	CONSTRAINT FK_ID_VEICULO__CLIENTES_VEICULOS FOREIGN KEY (ID_VEICULO)
	REFERENCES VEICULOS (ID_VEICULO)
)
GO

CREATE TABLE PRODUTOS(
	ID_PRODUTO INT IDENTITY(1,1) NOT NULL,
	NOME_PRODUTO VARCHAR(50) NOT NULL,
	MARCA VARCHAR(25) NULL, --DIVIDIR EM POSSIVEL TABELA DE MARCAS
	LINHA VARCHAR(25) NULL,
	QTD_ESTOQUE INT NULL

	CONSTRAINT PK_ID_PRODUTO PRIMARY KEY (ID_PRODUTO)
)
GO

CREATE TABLE PROCEDIMENTOS(
	ID_PROCEDIMENTO INT IDENTITY(1,1) NOT NULL,
	NOME_PROCEDIMENTO VARCHAR(50) NOT NULL,
	OBSERVACOES VARCHAR(500) NULL

	CONSTRAINT PK_ID_PROCEDIMENTO PRIMARY KEY (ID_PROCEDIMENTO)
)
GO

CREATE TABLE ENTRADAS_ESTOQUE(
	ID_ENTRADA INT IDENTITY(1,1) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	NOME_PRODUTO VARCHAR(50) NOT NULL,
	QTD_ENTRADA INT NOT NULL, 
	DT_ENTRADA DATETIME NOT NULL,
	DT_ULTIMA_ALTERACAO DATETIME NULL,
	NUM_ITENS_ATUAL INT NOT NULL,
	PRECO_UN NUMERIC(7,2) NOT NULL,
	NUM_NOTA_FISCAL INT NULL,
	LOTE VARCHAR(20) NOT NULL,
	ABERTO BIT NOT NULL

	CONSTRAINT PK_ID_ENTRADA PRIMARY KEY (ID_ENTRADA),

	CONSTRAINT FK_ID_PRODUTO__ENTRADAS_ESTOQUE FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTOS (ID_PRODUTO)
)
GO

CREATE TABLE SAIDAS_ESTOQUE(
	ID_SAIDA INT IDENTITY(1,1) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	NOME_PRODUTO VARCHAR(50),
	QTD_SAIDA INT NOT NULL,
	PRECO_VENDA_UN NUMERIC(7,2) NOT NULL

	CONSTRAINT PK_ID_SAIDA PRIMARY KEY (ID_SAIDA),

	CONSTRAINT FK_ID_PRODUTO__SAIDAS_ESTOQUE FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTOS (ID_PRODUTO)
)
GO

CREATE TABLE ORDENS_SERVICOS(
	ID_ORDEM_SERVICO INT IDENTITY(1,1) NOT NULL,
	DT_SOLICITACAO DATETIME NOT NULL,
	DT_CONCLUSAO DATETIME NOT NULL,
	ID_CLIENTE INT NOT NULL, 
	VALOR_TOTAL NUMERIC(7,2) NOT NULL,
	NUM_NOTA_FISCAL INT NULL,
	OBSERVACOES VARCHAR(500) NULL

	CONSTRAINT PK_ID_ORDEM_SERVICO PRIMARY KEY (ID_ORDEM_SERVICO),

	CONSTRAINT FK_ID_CLIENTE__ORDENS_SERVICOS FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTES (ID_CLIENTE)
)
GO

CREATE TABLE PRODUTOS_ORDENS_SERVICOS(
	ID_ORDEM_SERVICO INT NOT NULL,
	ID_PRODUTO INT NULL,
	ID_PROCEDIMENTO INT NULL,
	QTD_PRODUTO INT NOT NULL

	CONSTRAINT FK_ID_ORDEM_SERVICO__PRODUTOS_ORDENS_SERVICOS FOREIGN KEY (ID_ORDEM_SERVICO)
	REFERENCES ORDENS_SERVICOS (ID_ORDEM_SERVICO),

	CONSTRAINT FK_ID_PRODUTO__PRODUTOS_ORDENS_SERVICOS FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTOS (ID_PRODUTO),

	CONSTRAINT FK_ID_PROCEDIMENTO__PRODUTOS_ORDENS_SERVICOS FOREIGN KEY (ID_PROCEDIMENTO)
	REFERENCES PROCEDIMENTOS (ID_PROCEDIMENTO)
)
GO

CREATE TABLE TOTAL_PRODUTOS_ESTOQUE(
	ID_PRODUTO INT UNIQUE NOT NULL ,
	NOME_PRODUTO VARCHAR(50) NOT NULL,
	QTD_ESTOQUE INT NOT NULL,
	PRECO_UND NUMERIC(7,2) NOT NULL,
	LOTE_ATUAL VARCHAR(20) NOT NULL

	CONSTRAINT FK_ID_PRODUTO__TOTAL_PRODUTOS_ESTOQUE FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTOS (ID_PRODUTO)
)
GO
