/*-------------------------------------------------------------------------------
Nome: sp_Retira_Itens_Estoque
Data de Criação: 15/09/2022
Autor: Ícaro Rodrigues

Alterações: Removido as condicionais caso não haja o numero de itens necessário em estoque, 
			devido à tabela "TOTAL_PRODUTOS_ESTOQUE" já possuir essa informação totalizada.
-------------------------------------------------------------------------------*/

If Exists (Select 1 From Sysobjects Where Id = Object_Id('dbo.sp_Retira_Itens_Estoque'))
     Drop Procedure dbo.sp_Retira_Itens_Estoque
Go

Create Procedure dbo.sp_Retira_Itens_Estoque
(
       @ID_PRODUTO INT
     , @N_ITENS_REMOVIDOS INT
) As
Begin
     Set NoCount On;
     DECLARE
			@N_ITENS_PACOTE_ATUAL INT
		  , @QTD_SOBRA INT


	SELECT @N_ITENS_PACOTE_ATUAL = EE.NUM_ITENS_ATUAL

	FROM ENTRADAS_ESTOQUE EE
		JOIN TOTAL_PRODUTOS_ESTOQUE TPE
			ON (EE.ID_PRODUTO = TPE.ID_PRODUTO
				AND EE.LOTE = TPE.LOTE_ATUAL)

	WHERE 0 = 0 
		AND EE.ID_PRODUTO = @ID_PRODUTO
		AND EE.ABERTO = 1



	 IF ((SELECT QTD_ESTOQUE FROM TOTAL_PRODUTOS_ESTOQUE WHERE ID_PRODUTO = @ID_PRODUTO) > @N_ITENS_REMOVIDOS) -- SE O NUMERO DE ITENS NO ESTOQUE FOR MAIOR QUE A RETIRADA
		BEGIN
			IF(@N_ITENS_REMOVIDOS > @N_ITENS_PACOTE_ATUAL) --SE O NUMERO DE ITENS RETIRADOS FOR MAIOR QUE A QTD DE ITENS DO PACOTE ATUAL EM ABERTO
			BEGIN
				SELECT @QTD_SOBRA = @N_ITENS_REMOVIDOS - @N_ITENS_PACOTE_ATUAL

				EXEC dbo.sp_Atualiza_Lote_Estoque @ID_PRODUTO --ZERA E FECHA O PACOTE ATUAL QUE SE ESGOTOU E ABRE O PROXIMO

				UPDATE ENTRADAS_ESTOQUE --ATUALIZA A QUANTIDADE DE ITENS RESTANTES DO NOVO PACOTE EM ABERTO
				SET NUM_ITENS_ATUAL = EE.NUM_ITENS_ATUAL - @QTD_SOBRA
				FROM ENTRADAS_ESTOQUE EE
				WHERE EE.ID_PRODUTO = @ID_PRODUTO
					AND ABERTO = 1
					AND NUM_ITENS_ATUAL > 0
			END
		
			--ATUALIZA A QUANTIDADE NA TABELA DE ESTOQUE
			BEGIN
				 UPDATE TOTAL_PRODUTOS_ESTOQUE
				 SET QTD_ESTOQUE = TPE.QTD_ESTOQUE - @N_ITENS_REMOVIDOS
				 FROM TOTAL_PRODUTOS_ESTOQUE TPE
				 WHERE ID_PRODUTO = @ID_PRODUTO

				 UPDATE ENTRADAS_ESTOQUE --ATUALIZA A QUANTIDADE DE ITENS RESTANTES DO NOVO PACOTE EM ABERTO
				 SET NUM_ITENS_ATUAL = EE.NUM_ITENS_ATUAL - @N_ITENS_REMOVIDOS
				 FROM ENTRADAS_ESTOQUE EE
				 WHERE EE.ID_PRODUTO = @ID_PRODUTO
					AND ABERTO = 1
					AND NUM_ITENS_ATUAL > 0
			END
		END

	ELSE IF((SELECT QTD_ESTOQUE FROM TOTAL_PRODUTOS_ESTOQUE WHERE ID_PRODUTO = @ID_PRODUTO) < @N_ITENS_REMOVIDOS) --SE NAO EXISTIR A QUANTIDADE DE ITENS NO ESTOQUE
		BEGIN
			PRINT 'A QUANTIDADE DE ITENS SOLICITADOS NÃO EXISTE NO ESTOQUE'
		END
		
     Set NoCount Off;
End
Go



