/*-------------------------------------------------------------------------------
Nome: sp_Retira_Itens_Estoque
Data de Criação: 15/09/2022
Autor: Ícaro Rodrigues

Alterações: Removido as condicionais caso não haja o numero de itens necessário em estoque, 
			devido à tabela "TOTAL_PRODUTOS_ESTOQUE" já possuir essa informação totalizada.
-------------------------------------------------------------------------------*/

If Exists (Select 1 From Sysobjects Where Id = Object_Id('dbo.sp_Retira_Itens_Estoque'))
     Drop Procedure dbo.sp_Retira_Itens_Estoque
Go

Create Procedure dbo.sp_Retira_Itens_Estoque
(
       @ID_PRODUTO INT
     , @N_ITENS_REMOVIDOS INT
) As
Begin
     Set NoCount On;
     DECLARE
			@N_ITENS_PACOTE_ATUAL INT
		  , @QTD_SOBRA INT


	SELECT @N_ITENS_PACOTE_ATUAL = EE.NUM_ITENS_ATUAL

	FROM ENTRADAS_ESTOQUE EE
		JOIN TOTAL_PRODUTOS_ESTOQUE TPE
			ON (EE.ID_PRODUTO = TPE.ID_PRODUTO
				AND EE.LOTE = TPE.LOTE_ATUAL)

	WHERE 0 = 0 
		AND EE.ID_PRODUTO = @ID_PRODUTO
		AND EE.ABERTO = 1



	 IF ((SELECT QTD_ESTOQUE FROM TOTAL_PRODUTOS_ESTOQUE WHERE ID_PRODUTO = @ID_PRODUTO) > @N_ITENS_REMOVIDOS) -- SE O NUMERO DE ITENS NO ESTOQUE FOR MAIOR QUE A RETIRADA
		BEGIN
			IF(@N_ITENS_REMOVIDOS > @N_ITENS_PACOTE_ATUAL) --SE O NUMERO DE ITENS RETIRADOS FOR MAIOR QUE A QTD DE ITENS DO PACOTE ATUAL EM ABERTO
			BEGIN
				SELECT @QTD_SOBRA = @N_ITENS_REMOVIDOS - @N_ITENS_PACOTE_ATUAL

				BEGIN
					EXEC dbo.sp_Atualiza_Lote_Estoque @ID_PRODUTO --ZERA E FECHA O PACOTE ATUAL QUE SE ESGOTOU E ABRE O PROXIMO
				END

				BEGIN
					UPDATE ENTRADAS_ESTOQUE --ATUALIZA A QUANTIDADE DE ITENS RESTANTES DO NOVO PACOTE EM ABERTO
					SET NUM_ITENS_ATUAL = (EE.NUM_ITENS_ATUAL - @QTD_SOBRA)
					FROM ENTRADAS_ESTOQUE EE
					WHERE EE.ID_PRODUTO = @ID_PRODUTO
						AND ABERTO = 1
						AND NUM_ITENS_ATUAL > 0
				END
			END

			--SE HOUVER ITENS SUFICIENTE NO PACOTE ATUAL, SÓ REALIZA A REMOÇÃO
			ELSE IF(@N_ITENS_REMOVIDOS < @N_ITENS_PACOTE_ATUAL)
			BEGIN
				UPDATE ENTRADAS_ESTOQUE
				SET NUM_ITENS_ATUAL = (EE.NUM_ITENS_ATUAL - @N_ITENS_REMOVIDOS)
				FROM ENTRADAS_ESTOQUE EE
				WHERE  0 = 0 
					AND ID_PRODUTO = @ID_PRODUTO
					AND ABERTO = 1
					AND NUM_ITENS_ATUAL > 0
			END
		
			--ATUALIZA A QUANTIDADE NA TABELA DE ESTOQUE
			BEGIN
				 EXEC dbo.sp_Totaliza_Itens_Estoque @ID_PRODUTO
			END

			--CRIA A SAIDA DO ESTOQUE ---------------------------------------------------------------
			BEGIN
				--
				DECLARE
					@NOME_PRODUTO VARCHAR(50),
					@PRECO_VENDA NUMERIC(7,2)

					SELECT @NOME_PRODUTO = P.NOME_PRODUTO,
						   @PRECO_VENDA = EE.PRECO_UN

					FROM PRODUTOS P
						LEFT JOIN ENTRADAS_ESTOQUE EE
							ON (P.ID_PRODUTO = EE.ID_PRODUTO)

					WHERE P.ID_PRODUTO = @ID_PRODUTO
						AND EE.ABERTO = 1

				--SERÁ NECESSÁRIO CRIAR UMA NOVA COLUNA NA TABELA "TOTAL_PRODUTOS_ESTOQUE" OU EM "ENTRADAS_ESTOQUE" PARA GUARDAR O PREÇO DE VENDA
				--UTILIZANDO O VALOR DE ENTRADA DO ESTOQUE COMO PREÇO DE VENDA, MAS SERÁ NECESSÁRIO AJUSTAR
				BEGIN
					INSERT SAIDAS_ESTOQUE ([ID_PRODUTO], [NOME_PRODUTO], [QTD_SAIDA], [PRECO_VENDA_UN])
					VALUES (@ID_PRODUTO, @NOME_PRODUTO, @N_ITENS_REMOVIDOS, @PRECO_VENDA)
				END
			END

		END

	ELSE IF((SELECT QTD_ESTOQUE FROM TOTAL_PRODUTOS_ESTOQUE WHERE ID_PRODUTO = @ID_PRODUTO) < @N_ITENS_REMOVIDOS) --SE NAO EXISTIR A QUANTIDADE DE ITENS NO ESTOQUE
		BEGIN
			PRINT 'A QUANTIDADE DE ITENS SOLICITADOS NÃO EXISTE NO ESTOQUE'
		END
		
     Set NoCount Off;
End
Go



